version: "3.8"

# This compose file demonstrates how to wire up the published
# dfiore/eventsschedule:latest image without rebuilding from source.
# Copy it next to your .env file, then run `docker compose -f docker-compose.prebuilt.yml up -d`.

services:
  app:
    image: dfiore/eventsschedule:latest
    pull_policy: if_not_present
    env_file: ../.env
    environment:
      DB_PASSWORD: ${DB_PASSWORD:-change_me}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - storage:/var/www/html/storage
      - vendor:/var/www/html/vendor
      - node_modules:/var/www/html/node_modules
    entrypoint: ["/usr/local/bin/docker-entrypoint.sh"]
    command: ["php-fpm", "-F"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 9000"]
      interval: 5s
      timeout: 3s
      retries: 30

  web:
    image: dfiore/eventsschedule:latest
    pull_policy: if_not_present
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "8080:80"
    volumes:
      - storage:/var/www/html/storage:ro
    command: ["/usr/sbin/nginx", "-g", "daemon off;"]
    restart: unless-stopped

  db:
    image: mariadb:11
    environment:
      MYSQL_DATABASE: eventschedule
      MYSQL_USER: eventschedule
      MYSQL_PASSWORD: ${DB_PASSWORD:-change_me}
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "127.0.0.1", "-uroot", "-prootpass"]
      interval: 5s
      timeout: 3s
      retries: 40
    restart: unless-stopped

  scheduler:
    image: dfiore/eventsschedule:latest
    pull_policy: if_not_present
    depends_on:
      db:
        condition: service_healthy
    env_file: ../.env
    environment:
      DB_PASSWORD: ${DB_PASSWORD:-change_me}
    command: ["sh", "-lc", "while :; do php artisan schedule:run --verbose --no-interaction || true; sleep 60; done"]
    restart: unless-stopped
    volumes:
      - storage:/var/www/html/storage
      - vendor:/var/www/html/vendor
      - node_modules:/var/www/html/node_modules

volumes:
  dbdata:
  storage:
  vendor:
  node_modules:
